#!/usr/bin/env bash
# Shared helper: runs dotnet test with coverage and enforces the 90% threshold.
# Called by pre-commit and pre-push — do not run directly.

set -uo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

RESULTS_DIR="test/Alignd.Tests/TestResults/hook"

echo ""
echo "========================================================="
echo "  Running backend coverage check..."
echo "========================================================="
echo ""

# Remove stale results so we always parse a fresh report.
rm -rf "$RESULTS_DIR"

# Run tests with coverage collection.
dotnet test test/Alignd.Tests/ \
    --settings coverage.runsettings \
    --collect:"XPlat Code Coverage" \
    --results-directory "$RESULTS_DIR" \
    --verbosity minimal
TEST_EXIT=$?

if [ $TEST_EXIT -ne 0 ]; then
    echo ""
    echo "BLOCKED: One or more tests failed."
    echo "Fix the failing tests before you commit or push."
    echo ""
    exit 1
fi

# Locate the Cobertura report generated by Coverlet.
COVERAGE_FILE=$(find "$RESULTS_DIR" -name "coverage.cobertura.xml" 2>/dev/null | head -1)

if [ -z "$COVERAGE_FILE" ]; then
    echo ""
    echo "BLOCKED: Coverage report (coverage.cobertura.xml) was not found."
    echo "Make sure the 'XPlat Code Coverage' collector is configured correctly."
    echo ""
    exit 1
fi

# Resolve Python executable (python3 on Linux/macOS, python on Windows).
PYTHON_CMD=""
if command -v python3 &>/dev/null; then
    PYTHON_CMD="python3"
elif command -v python &>/dev/null; then
    PYTHON_CMD="python"
fi

if [ -z "$PYTHON_CMD" ]; then
    echo "WARNING: Python not found — cannot verify the 90% coverage threshold."
    echo "Install Python or add it to PATH to enable threshold enforcement."
    exit 0
fi

# Parse the line-rate from the root <coverage> element and compare.
RESULT=$("$PYTHON_CMD" - "$COVERAGE_FILE" <<'PYEOF'
import sys, xml.etree.ElementTree as ET
path = sys.argv[1]
rate = float(ET.parse(path).getroot().get('line-rate', '0'))
pct  = rate * 100
print('PASS' if rate >= 0.90 else 'FAIL', f'{pct:.1f}')
PYEOF
)

STATUS=$(echo "$RESULT" | cut -d' ' -f1)
PERCENT=$(echo "$RESULT" | cut -d' ' -f2)

if [ "$STATUS" = "FAIL" ]; then
    echo ""
    echo "BLOCKED: Line coverage is ${PERCENT}% — below the required 90% threshold."
    echo "Increase test coverage before you commit or push."
    echo ""
    exit 1
fi

echo ""
echo "OK: All tests passed. Line coverage: ${PERCENT}% (threshold: 90%)."
echo ""
exit 0
